region program ".program" ()
{
    var printf:any:(func,decl,align(4));
    var t1:i32:(align(4));
    var t2:i32:(align(4));
    var t3:i32:(align(4));
    var t4:i32:(align(4));
    var t5:i32:(align(4));
    var t6:i32:(align(4));
    var c:i32:(align(4));
    var d:i32:(align(4));
    var e:i32:(align(4));
    var k:i32:(align(4));
    var g:i32:(align(4));
    var h:i32:(align(4));
    var foo:any:(func,align(4));
    var foo1:any:(func,align(4));
    var foo2:any:(func,align(4));
    var foo3:any:(func,align(4));
    var foo4:any:(func,align(4));
    var foo5:any:(func,align(4));
    var main:any:(func,align(4));
    region func foo (undefined,var i:i32:(align(4))) {
        var l:i32:(align(4));
        var l2:i32:(align(4));
        var x:i32:(align(4));
        label "_GR__$L3";
        st:i32 l = 
            mul:i32 
                ld:i32 t5, 
                ld:i32 t3;
        st:i32 g = 
            mul:i32 
                ld:i32 t6, 
                ld:i32 t4;
        st:i32 l2 = 
            mul:i32 
                ld:i32 l, 7:i32;
        st:i32 h = 
            mul:i32 
                ld:i32 l2, 2:i32;
        stpr $3:i32 = 
            ld:i32 i;
        st:i32 i = 
            add:i32 
                ld:i32 i, 1:i32;
        label "_GR__$L1";
        phi $4:i32 = (
            $3:i32,"_GR__$L3"),(
            $5:i32,"_GR__$L4");
        falsebr (
            lt:bool 
                $4:i32, 10:i32), "_GR__$L2";
        label "_GR__$L4";
        st:i32 e = 
            add:i32 
                ld:i32 e, 1:i32;
        stpr $5:i32 = 
            ld:i32 i;
        st:i32 i = 
            add:i32 
                ld:i32 i, 1:i32;
        goto "_GR__$L1";
        label "_GR__$L2";
        st:i32 x = 
            mul:i32 
                ld:i32 g, 
                ld:i32 h;
        st:i32 x = 
            mul:i32 
                ld:i32 x, 3:i32;
        return 
            ld:i32 x;
    };
    //==---- DUMP Region 'foo1' ----==
    region func foo1 (undefined,var i:i32:(align(4))) {

        var l:i32:(align(4));
        var l2:i32:(align(4));
        var w:i32:(align(4));
        var u:i32:(align(4));
        var x:i32:(align(4));
        st:i32 l = 
            mul:i32 
                ld:i32 t5, 
                ld:i32 t3;
        st:i32 g = 
            mul:i32 
                ld:i32 t6, 
                ld:i32 t4;
        st:i32 l2 = 
            mul:i32 
                ld:i32 l, 7:i32;
        st:i32 h = 
            mul:i32 
                ld:i32 l2, 2:i32;
        st:i32 k = 
            add:i32 
                ld:i32 t3, 4:i32;
        st:i32 d = 
            add:i32 
                add:i32 
                    ld:i32 t2, 20:i32, 
                ld:i32 k;
        stpr $1:i32 = 
            ld:i32 i;
        st:i32 i = 
            add:i32 
                ld:i32 i, 1:i32;
        while (
            lt:bool 
                $1:i32, 10:i32) {
            stpr $2:i32 = 
                ld:i32 e;
            st:i32 e = 
                add:i32 
                    ld:i32 e, 1:i32;
            stpr $1:i32 = 
                ld:i32 i;
            st:i32 i = 
                add:i32 
                    ld:i32 i, 1:i32;
        };
        st:i32 w = 
            add:i32 
                ld:i32 t1, 
                ld:i32 d;
        st:i32 u = 
            add:i32 
                ld:i32 t1, 
                ld:i32 d;
        st:i32 x = 
            mul:i32 
                ld:i32 g, 
                ld:i32 h;
        return 
            add:i32 
                add:i32 
                    ld:i32 w, 
                    ld:i32 u, 
                ld:i32 x;
    };
    //==---- DUMP Region 'foo2' ----==
    region func foo2 (undefined,var i:i32:(align(4))) {

        st:i32 d = 
            add:i32 
                ld:i32 t2, 23:i32;
        if (
            gt:bool 
                ld:i32 i, 0:i32)
        {
            st:i32 e = 20:i32;
        };
        return 
            add:i32 
                ld:i32 t1, 
                ld:i32 d;
    };
    //==---- DUMP Region 'foo3' ----==
    region func foo3 () {

        st:i32 c = 
            add:i32 
                add:i32 
                    add:i32 
                        ld:i32 t1, 10:i32, 
                    ld:i32 t2, 20:i32;
        return 0:i32;
    };
    //==---- DUMP Region 'foo4' ----==
    region func foo4 () {

        st:i32 c = 
            add:i32 
                add:i32 
                    add:i32 
                        add:i32 
                            ld:i32 t1, 12:i32, 
                        add:i32 
                            ld:i32 t2, 20:i32, 3:i32, 
                add:i32 
                    ld:i32 t3, 30:i32;
        return 0:i32;
    };
    //==---- DUMP Region 'foo5' ----==
    region func foo5 (undefined,var i:i32:(align(4))) {

        st:i32 d = 
            add:i32 
                ld:i32 t2, 23:i32;
        if (
            gt:bool 
                ld:i32 i, 0:i32)
        {
            st:i32 e = 20:i32;
        };
        st:i32 c = 
            add:i32 
                add:i32 
                    add:i32 
                        ld:i32 t1, 12:i32, 
                    ld:i32 d, 
                add:i32 
                    ld:i32 t3, 30:i32;
        return 0:i32;
    };
    //==---- DUMP Region 'main' ----==
    region func main () {

        st:i32 t1 = 3:i32;
        st:i32 t2 = 4:i32;
        st:i32 t3 = 5:i32;
        st:i32 t4 = 6:i32;
        st:i32 t5 = 7:i32;
        st:i32 t6 = 8:i32;
        st:i32 c = 0:i32;
        st:i32 d = 0:i32;
        st:i32 e = 0:i32;
        st:i32 k = 0:i32;
        st:i32 g = 0:i32;
        st:i32 h = 0:i32;
        call $1:i32 = foo(1:i32);
        if (
            lor:bool 
                lor:bool 
                    lor:bool 
                        lor:bool 
                            lor:bool 
                                ne:bool 
                                    ld:i32 c, 0:i32, 
                                ne:bool 
                                    ld:i32 d, 0:i32, 
                            ne:bool 
                                ld:i32 e, 9:i32, 
                        ne:bool 
                            ld:i32 k, 0:i32, 
                    ne:bool 
                        ld:i32 g, 48:i32, 
                ne:bool 
                    ld:i32 h, 490:i32)
        {
            return 1:i32;
        };
        call $2:i32 = foo1(0:i32);
        if (
            lor:bool 
                lor:bool 
                    lor:bool 
                        lor:bool 
                            lor:bool 
                                ne:bool 
                                    ld:i32 c, 0:i32, 
                                ne:bool 
                                    ld:i32 d, 33:i32, 
                            ne:bool 
                                ld:i32 e, 19:i32, 
                        ne:bool 
                            ld:i32 k, 9:i32, 
                    ne:bool 
                        ld:i32 g, 48:i32, 
                ne:bool 
                    ld:i32 h, 490:i32)
        {
            return 2:i32;
        };
        call $3:i32 = foo2(1:i32);
        if (
            lor:bool 
                lor:bool 
                    lor:bool 
                        lor:bool 
                            lor:bool 
                                ne:bool 
                                    ld:i32 c, 0:i32, 
                                ne:bool 
                                    ld:i32 d, 27:i32, 
                            ne:bool 
                                ld:i32 e, 20:i32, 
                        ne:bool 
                            ld:i32 k, 9:i32, 
                    ne:bool 
                        ld:i32 g, 48:i32, 
                ne:bool 
                    ld:i32 h, 490:i32)
        {
            return 3:i32;
        };
        call $4:i32 = foo3();
        if (
            lor:bool 
                lor:bool 
                    lor:bool 
                        lor:bool 
                            lor:bool 
                                ne:bool 
                                    ld:i32 c, 37:i32, 
                                ne:bool 
                                    ld:i32 d, 27:i32, 
                            ne:bool 
                                ld:i32 e, 20:i32, 
                        ne:bool 
                            ld:i32 k, 9:i32, 
                    ne:bool 
                        ld:i32 g, 48:i32, 
                ne:bool 
                    ld:i32 h, 490:i32)
        {
            return 4:i32;
        };
        call $5:i32 = foo4();
        if (
            lor:bool 
                lor:bool 
                    lor:bool 
                        lor:bool 
                            lor:bool 
                                ne:bool 
                                    ld:i32 c, 77:i32, 
                                ne:bool 
                                    ld:i32 d, 27:i32, 
                            ne:bool 
                                ld:i32 e, 20:i32, 
                        ne:bool 
                            ld:i32 k, 9:i32, 
                    ne:bool 
                        ld:i32 g, 48:i32, 
                ne:bool 
                    ld:i32 h, 490:i32)
        {
            return 5:i32;
        };
        call $6:i32 = foo5(1:i32);
        if (
            lor:bool 
                lor:bool 
                    lor:bool 
                        lor:bool 
                            lor:bool 
                                ne:bool 
                                    ld:i32 c, 77:i32, 
                                ne:bool 
                                    ld:i32 d, 27:i32, 
                            ne:bool 
                                ld:i32 e, 20:i32, 
                        ne:bool 
                            ld:i32 k, 9:i32, 
                    ne:bool 
                        ld:i32 g, 48:i32, 
                ne:bool 
                    ld:i32 h, 490:i32)
        {
            return 6:i32;
        };
        return 0:i32;
    };
    st:i32 t1 = 3:i32;
    st:i32 t2 = 4:i32;
    st:i32 t3 = 5:i32;
    st:i32 t4 = 6:i32;
    st:i32 t5 = 7:i32;
    st:i32 t6 = 8:i32;
    st:i32 c = 0:i32;
    st:i32 d = 0:i32;
    st:i32 e = 0:i32;
    st:i32 k = 0:i32;
    st:i32 g = 0:i32;
    st:i32 h = 0:i32;
}
