COM_OBJS +=\
../com/ltype.o \
../com/xmat.o \
../com/comf.o \
../com/strbuf.o \
../com/smempool.o \
../com/agraph.o \
../com/sgraph.o \
../com/rational.o \
../com/testbs.o \
../com/flty.o \
../com/linsys.o \
../com/bs.o
