/*@
Copyright (c) 2013-2021, Su Zhenyu steven.known@gmail.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Su Zhenyu nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED "AS IS" AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
@*/
#include "cominc.h"
#include "comopt.h"

namespace xoc {

IRDesc const g_ir_desc[] = {
    { IR_UNDEF, "undef", 0x0, 0,
      0,
      0,
      dumpUNDEF,
      NOVERIFYFUNC,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_CONST, "const", CConst::kid_map, CConst::kid_num,
      sizeof(CConst),
      IRC_IS_LEAF,
      dumpConst,
      verifyConst,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_ID, "id", CId::kid_map, CId::kid_num,
      sizeof(CId),
      IRC_HAS_IDINFO|IRC_IS_MEM_REF|IRC_IS_LEAF|IRC_IS_NON_PR_MEMREF|
      IRC_IS_MEM_OPND|IRC_HAS_DU,
      dumpGeneral,
      verifyGeneral,
      NOACCRHSFUNC,
      CId::accIdinfo,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_LD, "ld", CLd::kid_map, CLd::kid_num,
      sizeof(CLd),
      IRC_HAS_IDINFO|IRC_IS_MEM_REF|IRC_IS_MEM_OPND|IRC_IS_LEAF|
      IRC_IS_NON_PR_MEMREF|IRC_HAS_DU|IRC_HAS_OFFSET|IRC_IS_DIRECT_MEM_OP|
      IRC_HAS_STORAGE_SPACE,
      dumpGeneral,
      verifyLD,
      NOACCRHSFUNC,
      CLd::accIdinfo,
      CLd::accOfst,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      CLd::accSS, },

    { IR_ILD, "ild", CILd::kid_map, CILd::kid_num,
      sizeof(CILd),
      IRC_IS_MEM_REF|IRC_IS_MEM_OPND|
      IRC_IS_NON_PR_MEMREF|IRC_HAS_DU|IRC_HAS_OFFSET|IRC_IS_INDIRECT_MEM_OP|
      IRC_HAS_STORAGE_SPACE,
      dumpGeneral,
      verifyILD,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      CILd::accOfst,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CILd::accKid,
      NOACCBBFUNC,
      CILd::accBase,
      NOACCLABFUNC,
      NOACCDETFUNC,
      CILd::accSS, },

    { IR_PR, "pr", CPr::kid_map, CPr::kid_num,
      sizeof(CPr),
      IRC_IS_MEM_REF|IRC_IS_MEM_OPND|IRC_IS_LEAF|IRC_HAS_DU,
      dumpReadPR,
      verifyPR,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      CPr::accSSAInfo,
      CPr::accPrno,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_ARRAY, "array", CArray::kid_map, CArray::kid_num,
      sizeof(CArray),
      IRC_IS_MEM_REF|IRC_IS_MEM_OPND|IRC_IS_NON_PR_MEMREF|
      IRC_HAS_DU|IRC_HAS_OFFSET|IRC_IS_ARRAY_OP|IRC_HAS_STORAGE_SPACE,
      dumpARRAY,
      verifyArrayOp,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      CArray::accOfst,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CArray::accKid,
      NOACCBBFUNC,
      CArray::accBase,
      NOACCLABFUNC,
      NOACCDETFUNC,
      CArray::accSS, },

    { IR_ST, "st", CSt::kid_map, CSt::kid_num,
      sizeof(CSt),
      IRC_HAS_IDINFO|IRC_IS_STMT|IRC_IS_MEM_REF|IRC_HAS_RESULT|
      IRC_IS_STMT_IN_BB|IRC_IS_NON_PR_MEMREF|IRC_HAS_DU|IRC_HAS_OFFSET|
      IRC_IS_DIRECT_MEM_OP|IRC_HAS_RHS|IRC_HAS_STORAGE_SPACE,
      dumpGeneral,
      verifyST,
      CSt::accRHS,
      CSt::accIdinfo,
      CSt::accOfst,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CSt::accKid,
      CSt::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      CSt::accSS, },

    { IR_STPR, "stpr", CStpr::kid_map, CStpr::kid_num,
      sizeof(CStpr),
      IRC_IS_STMT|IRC_IS_MEM_REF|IRC_HAS_RESULT|
      IRC_IS_STMT_IN_BB|IRC_HAS_DU|IRC_IS_WRITE_PR|IRC_IS_WRITE_WHOLE_PR|
      IRC_HAS_RHS,
      dumpWritePR,
      verifySTPR,
      CStpr::accRHS,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      CStpr::accSSAInfo,
      CStpr::accPrno,
      CStpr::accResultPR,
      CStpr::accKid,
      CStpr::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_STARRAY, "starray", CStArray::kid_map, CStArray::kid_num,
      sizeof(CStArray),
      IRC_IS_STMT|IRC_IS_MEM_REF|IRC_HAS_RESULT|
      IRC_IS_STMT_IN_BB|IRC_IS_NON_PR_MEMREF|IRC_HAS_DU|IRC_HAS_OFFSET|
      IRC_IS_ARRAY_OP|IRC_HAS_RHS|IRC_HAS_STORAGE_SPACE,
      dumpSTARRAY,
      verifyArrayOp,
      CStArray::accRHS,
      NOACCIDINFOFUNC,
      CStArray::accOfst,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CStArray::accKid,
      CStArray::accBB,
      CStArray::accBase,
      NOACCLABFUNC,
      NOACCDETFUNC,
      CStArray::accSS, },

    { IR_IST, "ist", CISt::kid_map, CISt::kid_num,
      sizeof(CISt),
      IRC_IS_STMT|IRC_IS_MEM_REF|IRC_HAS_RESULT|
      IRC_IS_STMT_IN_BB|IRC_IS_NON_PR_MEMREF|IRC_HAS_DU|IRC_HAS_OFFSET|
      IRC_IS_INDIRECT_MEM_OP|IRC_HAS_RHS|IRC_HAS_STORAGE_SPACE,
      dumpGeneral,
      verifyIST,
      CISt::accRHS,
      NOACCIDINFOFUNC,
      CISt::accOfst,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CISt::accKid,
      CISt::accBB,
      CISt::accBase,
      NOACCLABFUNC,
      NOACCDETFUNC,
      CISt::accSS, },

    { IR_SETELEM, "setelem", CSetElem::kid_map, CSetElem::kid_num,
      sizeof(CSetElem),
      IRC_IS_STMT|IRC_IS_MEM_REF|IRC_HAS_RESULT|
      IRC_IS_STMT_IN_BB|IRC_HAS_DU|IRC_IS_WRITE_PR,
      dumpWritePR,
      verifySETELEM,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      CSetElem::accSSAInfo,
      CSetElem::accPrno,
      CSetElem::accResultPR,
      CSetElem::accKid,
      CSetElem::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_GETELEM, "getelem", CGetElem::kid_map, CGetElem::kid_num,
      sizeof(CGetElem),
      IRC_IS_STMT|IRC_IS_MEM_REF|IRC_HAS_RESULT|
      IRC_IS_STMT_IN_BB|IRC_HAS_DU|IRC_IS_WRITE_PR|IRC_IS_WRITE_WHOLE_PR,
      dumpWritePR,
      verifyGETELEM,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      CGetElem::accSSAInfo,
      CGetElem::accPrno,
      CGetElem::accResultPR,
      CGetElem::accKid,
      CGetElem::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    //CALL might not def PR if there is not return value.
    { IR_CALL, "call", CCall::kid_map, CCall::kid_num,
      sizeof(CCall),
      IRC_IS_STMT|IRC_IS_MEM_REF|IRC_HAS_RESULT|
      IRC_HAS_IDINFO|IRC_IS_STMT_IN_BB|IRC_HAS_DU|IRC_HAS_STORAGE_SPACE,
      dumpCallStmt,
      verifyCALL,
      NOACCRHSFUNC,
      CCall::accIdinfo,
      NOACCOFSTFUNC,
      CCall::accSSAInfo,
      CCall::accPrno,
      CCall::accResultPR,
      CCall::accKid,
      CCall::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      CCall::accSS, },

    { IR_ICALL, "icall", CICall::kid_map, CICall::kid_num,
      sizeof(CICall),
      IRC_IS_STMT|IRC_IS_MEM_REF|IRC_IS_STMT_IN_BB|IRC_HAS_DU|
      //ICALL might not define PR if there is not return value.
      IRC_HAS_RESULT,
      dumpCallStmt,
      verifyICALL,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      CICall::accSSAInfo,
      CICall::accPrno,
      CICall::accResultPR,
      CICall::accKid,
      CICall::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_LDA, "lda", CLda::kid_map, CLda::kid_num,
      sizeof(CLda),
      IRC_HAS_IDINFO|IRC_IS_LEAF|IRC_HAS_OFFSET|IRC_HAS_STORAGE_SPACE,
      dumpGeneral,
      verifyLDA,
      NOACCRHSFUNC,
      CLda::accIdinfo,
      CLda::accOfst,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      CLda::accSS, },

    { IR_ADD, "add", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_ASSOCIATIVE|IRC_IS_COMMUTATIVE,
      dumpBinAndUna,
      verifyADD,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_SUB, "sub", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_ASSOCIATIVE,
      dumpBinAndUna,
      verifyBin,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_MUL, "mul", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_ASSOCIATIVE|IRC_IS_COMMUTATIVE,
      dumpBinAndUna,
      verifyBin,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_DIV, "div", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN,
      dumpBinAndUna,
      verifyBin,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_REM, "rem", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN,
      dumpBinAndUna,
      verifyBin,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_MOD, "mod", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN,
      dumpBinAndUna,
      verifyBin,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_LAND, "land", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_LOGICAL,
      dumpBinAndUna,
      verifyCompare,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_LOR, "lor", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_LOGICAL,
      dumpBinAndUna,
      verifyCompare,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_BAND, "band", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_ASSOCIATIVE|IRC_IS_COMMUTATIVE,
      dumpBinAndUna,
      verifyBin,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_BOR, "bor", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_ASSOCIATIVE,
      dumpBinAndUna,
      verifyBin,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_XOR, "xor", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_ASSOCIATIVE|IRC_IS_COMMUTATIVE,
      dumpBinAndUna,
      verifyBin,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_ASR, "asr", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN,
      dumpBinAndUna,
      verifyShift,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_LSR, "lsr", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN,
      dumpBinAndUna,
      verifyShift,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_LSL, "lsl", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN,
      dumpBinAndUna,
      verifyShift,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_LT, "lt", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_RELATION,
      dumpBinAndUna,
      verifyCompare,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_LE, "le", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_RELATION,
      dumpBinAndUna,
      verifyCompare,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_GT, "gt", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_RELATION,
      dumpBinAndUna,
      verifyCompare,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_GE, "ge", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_RELATION,
      dumpBinAndUna,
      verifyCompare,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_EQ, "eq", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_ASSOCIATIVE|IRC_IS_COMMUTATIVE|IRC_IS_RELATION,
      dumpBinAndUna,
      verifyCompare,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_NE, "ne", CBin::kid_map, CBin::kid_num,
      sizeof(CBin),
      IRC_IS_BIN|IRC_IS_ASSOCIATIVE|IRC_IS_COMMUTATIVE|IRC_IS_RELATION,
      dumpBinAndUna,
      verifyCompare,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CBin::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_BNOT, "bnot", CUna::kid_map, CUna::kid_num,
      sizeof(CUna),
      IRC_IS_UNA,
      dumpBinAndUna,
      verifyUna,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CUna::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_LNOT, "lnot", CUna::kid_map, CUna::kid_num,
      sizeof(CUna),
      IRC_IS_UNA|IRC_IS_LOGICAL,
      dumpBinAndUna,
      verifyLNOT,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CUna::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_NEG, "neg", CUna::kid_map, CUna::kid_num,
      sizeof(CUna),
      IRC_IS_UNA,
      dumpBinAndUna,
      verifyUna,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CUna::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_CVT, "cvt", CCvt::kid_map, CCvt::kid_num,
      sizeof(CCvt),
      IRC_IS_UNA,
      dumpBinAndUna,
      verifyCVT,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CCvt::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_GOTO, "goto", CGoto::kid_map, CGoto::kid_num,
      sizeof(CGoto),
      IRC_IS_STMT|IRC_IS_STMT_IN_BB|IRC_IS_UNCONDITIONAL_BR,
      dumpBranch,
      verifyGOTO,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      CGoto::accBB,
      NOACCBASEFUNC,
      CGoto::accLab,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_IGOTO, "igoto", CIGoto::kid_map, CIGoto::kid_num,
      sizeof(CIGoto),
      IRC_IS_STMT|IRC_IS_STMT_IN_BB|IRC_IS_UNCONDITIONAL_BR|IRC_HAS_CASE_LIST,
      dumpGeneral,
      verifyIGOTO,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CIGoto::accKid,
      CIGoto::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_DO_WHILE, "dowhile", CDoWhile::kid_map, CDoWhile::kid_num,
      sizeof(CDoWhile),
      IRC_IS_STMT|IRC_HAS_JUDGE_TARGET,
      dumpDOWHILE,
      verifyLoopCFS,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CDoWhile::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      CDoWhile::accDet,
      NOACCSSFUNC, },

    { IR_WHILE_DO, "whiledo", CWhileDo::kid_map, CWhileDo::kid_num,
      sizeof(CWhileDo),
      IRC_IS_STMT|IRC_HAS_JUDGE_TARGET,
      dumpWHILEDO,
      verifyLoopCFS,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CWhileDo::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      CWhileDo::accDet,
      NOACCSSFUNC, },

    { IR_DO_LOOP, "doloop", CDoLoop::kid_map, CDoLoop::kid_num,
      sizeof(CDoLoop),
      IRC_IS_STMT|IRC_HAS_JUDGE_TARGET,
      dumpDOLOOP,
      verifyLoopCFS,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CDoLoop::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      CDoLoop::accDet,
      NOACCSSFUNC, },

    { IR_IF, "if", CIf::kid_map, CIf::kid_num,
      sizeof(CIf),
      IRC_IS_STMT|IRC_HAS_JUDGE_TARGET,
      dumpIF,
      verifyIF,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CIf::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      CIf::accDet,
      NOACCSSFUNC, },

    { IR_LABEL, "label", CLab::kid_map, CLab::kid_num,
      sizeof(CLab),
      IRC_IS_STMT,
      dumpLABEL,
      verifyNothing,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      CLab::accLab,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_SWITCH, "switch", CSwitch::kid_map, CSwitch::kid_num,
      sizeof(CSwitch),
      IRC_IS_STMT|IRC_IS_STMT_IN_BB|IRC_HAS_CASE_LIST,
      dumpSWITCH,
      verifySWITCH,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CSwitch::accKid,
      CSwitch::accBB,
      NOACCBASEFUNC,
      CSwitch::accLab,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_CASE, "case", CCase::kid_map, CCase::kid_num,
      sizeof(CCase),
      0,
      dumpCASE,
      verifyCASE,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CCase::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      CCase::accLab,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_TRUEBR, "truebr", CTruebr::kid_map, CTruebr::kid_num,
      sizeof(CTruebr),
      IRC_IS_STMT|IRC_IS_STMT_IN_BB|IRC_IS_CONDITIONAL_BR|IRC_HAS_JUDGE_TARGET,
      dumpBranch,
      verifyBranch,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CTruebr::accKid,
      CTruebr::accBB,
      NOACCBASEFUNC,
      CTruebr::accLab,
      CTruebr::accDet,
      NOACCSSFUNC, },

    { IR_FALSEBR, "falsebr", CFalsebr::kid_map, CFalsebr::kid_num,
      sizeof(CFalsebr),
      IRC_IS_STMT|IRC_IS_STMT_IN_BB|IRC_IS_CONDITIONAL_BR|IRC_HAS_JUDGE_TARGET,
      dumpBranch,
      verifyBranch,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CFalsebr::accKid,
      CFalsebr::accBB,
      NOACCBASEFUNC,
      CFalsebr::accLab,
      CFalsebr::accDet,
      NOACCSSFUNC, },

    { IR_RETURN, "return", CRet::kid_map, CRet::kid_num,
      sizeof(CRet),
      IRC_IS_STMT|IRC_IS_STMT_IN_BB,
      dumpRETURN,
      verifyRETURN,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CRet::accKid,
      CRet::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_SELECT, "select", CSelect::kid_map, CSelect::kid_num,
      sizeof(CSelect),
      IRC_HAS_JUDGE_TARGET,
      dumpSELECT,
      verifySELECT,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      CSelect::accKid,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      CSelect::accDet,
      NOACCSSFUNC, },

    { IR_BREAK, "break", CBreak::kid_map, CBreak::kid_num,
      sizeof(CBreak),
      IRC_IS_STMT,
      dumpGeneralNoType,
      verifyNothing,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_CONTINUE, "continue", CContinue::kid_map, CContinue::kid_num,
      sizeof(CContinue),
      IRC_IS_STMT,
      dumpGeneralNoType,
      verifyNothing,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_PHI, "phi", CPhi::kid_map, CPhi::kid_num,
      sizeof(CPhi),
      IRC_IS_STMT|IRC_HAS_RESULT|IRC_IS_MEM_REF|
      IRC_IS_STMT_IN_BB|IRC_HAS_DU|IRC_IS_WRITE_PR|IRC_IS_WRITE_WHOLE_PR,
      dumpPHI,
      verifyPHI,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      CPhi::accSSAInfo,
      CPhi::accPrno,
      CPhi::accResultPR,
      CPhi::accKid,
      CPhi::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    { IR_REGION, "region", CRegion::kid_map, CRegion::kid_num,
      sizeof(CRegion),
      IRC_IS_STMT|IRC_IS_STMT_IN_BB,
      dumpREGION,
      verifyNothing,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      CRegion::accBB,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },

    #include "ir_desc_ext.impl"

    { IR_CODE_NUM, "LAST IR CODE", 0x0, 0,
      0,
      0,
      NODUMPFUNC,
      NOVERIFYFUNC,
      NOACCRHSFUNC,
      NOACCIDINFOFUNC,
      NOACCOFSTFUNC,
      NOACCSSAINFOFUNC,
      NOACCPRNOFUNC,
      NOACCRESPRFUNC,
      NOACCKIDFUNC,
      NOACCBBFUNC,
      NOACCBASEFUNC,
      NOACCLABFUNC,
      NOACCDETFUNC,
      NOACCSSFUNC, },
};

RoundDesc const g_round_desc[] = {
    { ROUND_UNDEF, "undef" },
    { ROUND_DOWN, "down" },
    { ROUND_UP, "up" },
    { ROUND_TOWARDS_ZERO, "twards_zero" },
    { ROUND_AWAY_FROM_ZERO, "awayfromzero" },
    { ROUND_TO_NEAREST_INTEGER, "tonearestinteger" },
    { ROUND_HALF_UP, "halfup" },
    { ROUND_HALF_DOWN, "halfdown" },
    { ROUND_HALF_TOWARDS_ZERO, "halftowardszero" },
    { ROUND_HALF_AWAY_FROM_ZERO, "halfawayfromzero" },
    { ROUND_HALF_TO_EVEN, "halftoeven" },
    { ROUND_HALF_TO_ODD, "halftoodd" },
};

//The function only invoked at debug mode.
bool checkIRDesc()
{
    UINT sz = (UINT)(1 << IR_CODE_BIT_SIZE);
    ASSERTN(IR_CODE_NUM <= sz, ("code field is too small"));
    DUMMYUSE(sz);
    for (UINT i = IR_UNDEF; i < IR_CODE_NUM; i++) {
        ASSERT0(i == (UINT)IRDES_code(g_ir_desc[i]));
    }
    UINT descnum = sizeof(g_ir_desc) / sizeof(g_ir_desc[0]);
    ASSERTN_DUMMYUSE(descnum - 1 == IR_CODE_NUM, ("miss IRDesc declaration"));
    return true;
}


//The function only invoked at debug mode.
bool checkRoundDesc()
{
    for (UINT i = ROUND_UNDEF; i < ROUND_TYPE_NUM; i++) {
        ASSERT0(i == (UINT)ROUNDDESC_type(g_round_desc[i]));
    }
    UINT descnum = sizeof(g_round_desc) / sizeof(g_round_desc[0]);
    ASSERTN_DUMMYUSE(descnum == ROUND_TYPE_NUM, ("miss RoundDesc declaration"));
    return true;
}

} //namespace xoc
