OPT_OBJS +=\
../opt/cfs_opt.o\
../opt/dbg.o\
../opt/goto_opt.o\
../opt/if_opt.o \
../opt/du.o\
../opt/ir.o\
../opt/ir_bb.o\
../opt/ir_du.o\
../opt/ir_cfg.o\
../opt/ir_simp.o\
../opt/ir_gvn.o\
../opt/ir_rce.o\
../opt/ir_dce.o\
../opt/ir_cp.o\
../opt/ir_lcse.o\
../opt/ir_gcse.o\
../opt/ir_licm.o\
../opt/ir_middle_opt.o\
../opt/ir_high_opt.o\
../opt/ir_expr_tab.o\
../opt/cdg.o\
../opt/ir_refine.o\
../opt/ir_rp.o\
../opt/ir_aa.o\
../opt/ir_ssa.o\
../opt/ir_mdssa.o\
../opt/mdssainfo.o\
../opt/label.o\
../opt/data_type.o \
../opt/option.o\
../opt/region.o\
../opt/region_mgr.o\
../opt/util.o\
../opt/var.o\
../opt/md.o\
../opt/loop.o\
../opt/cfs_mgr.o\
../opt/pass_mgr.o\
../opt/inliner.o\
../opt/ipa.o\
../opt/callg.o\
../opt/ir_loop_cvt.o\
../opt/symtab.o

